### ISSUE TITLE
https://github.com/fperez/test.git no longer exists

### ISSUE THREAD

**Issue by wking** [fperez/reprosw#4]
So the reference to it in `Version Control.ipynb` should probably be removed or altered.

I think a local `git daemon` is the way to go for a reproducible remote example, since you can setup the remote repo, spawn the daemon, and interact with it from IPython.

**Comment by fperez** [comment]
Well, it's really meant to be for interactive teaching, so I destroy the repo and make it again in lecture.

Part of the point is to show the students how to interact with github, so I want to make it with a real-world example that also doesn't require setting up more exotic local tools.

The only issue is that it doesn't carry easily to a different lecturer, they'd need to change that one remote to one they control.  But in terms of keeping the flow around only local tools and github, I don't see a way around this.

**Comment by wking** [comment]
Ah, ok.  In that case, sorry for the spam :p.
